apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-domaindb
  labels:
    app: postgres-domaindb
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/domaindb"
    type: DirectoryOrCreate
