apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-organizationdb
  labels:
    app: postgres-organizationdb
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/organizationdb"
    type: DirectoryOrCreate
