apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-hostdb
  labels:
    app: postgres-hostdb
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/hostdb"
    type: DirectoryOrCreate
