apiVersion: apps/v1
kind: Deployment
metadata:
  name: domaincreate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domaincreate
  template:
    metadata:
      labels:
        app: domaincreate
    spec:
      containers:
      - name: domaincreate
        image: domaincreate:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: domaincreate-config
        ports:
        - containerPort: 3030
