{
 "title": "Performance monitor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total request calls",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gateway_routes_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "# requests last 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(gateway_routes_response_time_seconds_count[5m])) by (routeId)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time last 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(rate(gateway_routes_response_time_seconds_sum[5m])) by (routeId) \r\n  / avg(rate(gateway_routes_response_time_seconds_count[5m])) by (routeId)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}