apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: domain-postgresql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi