apiVersion: apps/v1
kind: Deployment
metadata:
  name: organizationcommand
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organizationcommand
  template:
    metadata:
      labels:
        app: organizationcommand
    spec:
      containers:
      - name: organizationcommand
        image: organizationcommand:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /config
        env:
        - name: ORGANIZATION_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: organization-postgresql
              key: password
        - name: SPRING_CONFIG_LOCATION
          value: "classpath:/application.yml,/config/application.yml"
      volumes:
      - name: config-volume
        configMap:
          name: organizationcommand-config