kubectl apply -f api-gateway/k8s
kubectl apply -f contactcreate/k8s
kubectl apply -f contactdelete/k8s
kubectl apply -f contactinfo/k8s
kubectl apply -f contactupdate/k8s
kubectl apply -f domaincreate/k8s
kubectl apply -f domaindelete/k8s
kubectl apply -f domaininfo/k8s 
kubectl apply -f domainupdate/k8s
kubectl delete pods --all
