apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-port-forward-binding
subjects:
- kind: ServiceAccount
  name: default  # Service account inside the job namespace
  namespace: {{ .Values.namespace | default "port-forward-ns" }} 
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-port-forward-role
  apiGroup: rbac.authorization.k8s.io
