apiVersion: v1
kind: ConfigMap
metadata:
  name: organization-migration-configmap
data:
  V1_1__create_table_organization.sql: |
    CREATE TABLE organization (
    id uuid DEFAULT gen_random_uuid(),  -- Unique identifier for the record
    organization_id TEXT NOT NULL,  -- Corresponding to <org:id>
    roid TEXT NOT NULL,  -- Corresponding to <org:roid>
    role_type TEXT,  -- Corresponding to <org:type>
    role_status TEXT[],  -- Corresponding to <org:status> (array to store multiple statuses)
    role_id INT,  -- Corresponding to <org:roleID>
    status TEXT[],  -- Store multiple status values for the registrar
    postal_info_type TEXT,  -- Corresponding to <org:postalInfo type="int">
    postal_info_name TEXT,  -- Corresponding to <org:name>
    postal_info_street TEXT[],  -- Store multiple street values
    postal_info_city TEXT,  -- Corresponding to <org:city>
    postal_info_state_province TEXT,  -- Corresponding to <org:sp>
    postal_info_postal_code TEXT,  -- Corresponding to <org:pc>
    postal_info_country_code TEXT,  -- Corresponding to <org:cc>
    voice TEXT,  -- Corresponding to <org:voice>
    fax TEXT,  -- Corresponding to <org:fax>
    email TEXT,  -- Corresponding to <org:email>
    url TEXT,  -- Corresponding to <org:url>
    contact_admin TEXT,  -- Corresponding to <org:contact type="admin">
    contact_billing TEXT,  -- Corresponding to <org:contact type="billing">
    contact_custom TEXT,  -- Corresponding to <org:contact type="custom" typeName="legal">
    cr_id TEXT,  -- Corresponding to <org:crID>
    cr_date TIMESTAMPTZ,  -- Corresponding to <org:crDate>
    up_id TEXT,  -- Corresponding to <org:upID>
    up_date TIMESTAMPTZ  -- Corresponding to <org:upDate>
    );
