spring:
  datasource:
    url: jdbc:h2:mem:testdb  # In-memory H2 database
    driver-class-name: org.h2.Driver
    username: sa  # Default H2 username
    password: ''  # No password for H2 by default
  jpa:
    hibernate:
      ddl-auto: none  # Disable JPA's automatic schema management, Flyway will handle it
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true  # Enable H2 web console for development
      path: /h2-console  # The path to access the H2 console
  flyway:
    enabled: true
    locations: classpath:/db/migration  # Directory where migration scripts are located
    schemas: domain  # Specify the schema to be used by Flyway
    default-schema: domain  # Optional: Set default schema for connections
service:
  simulated-workload: 1000000
management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "health", "info" ]
  endpoint:
    health:
      show:
        details: always