server:
  port: 8093
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/easysix
    driver-class-name: org.postgresql.Driver
    username: easysix
    password: easysix
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none  # Disable JPA's automatic schema management, Flyway will handle it
    properties:
      hibernate:
        default_schema: organization
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: false
        default_batch_fetch_size: 16
logging:
  level:
    org:
      hibernate:
        sql: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO
        orm:
          jdbc:
            bind: INFO