spring:
  datasource:
    url: jdbc:h2:mem:testdb  # In-memory H2 database
    driver-class-name: org.h2.Driver
    username: sa  # Default H2 username
    password: ''  # No password for H2 by default
  jpa:
    hibernate:
      ddl-auto: create  # Disable JPA's automatic schema management, Flyway will handle it
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true  # Enable H2 web console for development
      path: /h2-console  # The path to access the H2 console
management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "health", "info" ]
  endpoint:
    health:
      show:
        details: always