apiVersion: apps/v1
kind: Deployment
metadata:
  name: contactquery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contactquery
  template:
    metadata:
      labels:
        app: contactquery
    spec:
      containers:
      - name: contactquery
        image: contactquery:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: contactquery-config
        ports:
        - containerPort: 8080
