apiVersion: apps/v1
kind: Deployment
metadata:
  name: contactcommand
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contactcommand
  template:
    metadata:
      labels:
        app: contactcommand
    spec:
      containers:
      - name: contactcommand
        image: contactcommand:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /config
        env:
        - name: CONTACT_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: contact-postgresql
              key: password
        - name: SPRING_CONFIG_LOCATION
          value: "classpath:/application.yml,/config/application.yml"
      volumes:
      - name: config-volume
        configMap:
          name: contactcommand-config