apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostcommand
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostcommand
  template:
    metadata:
      labels:
        app: hostcommand
    spec:
      containers:
      - name: hostcommand
        image: hostcommand:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /config
        env:
        - name: ORGANIZATION_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: host-postgresql
              key: password
        - name: SPRING_CONFIG_LOCATION
          value: "classpath:/application.yml,/config/application.yml"
      volumes:
      - name: config-volume
        configMap:
          name: hostcommand-config