apiVersion: v1
kind: ConfigMap
metadata:
  name: contact-migration-configmap
data:
  V1_1__create_table_contact.sql: |
    CREATE TABLE "contact" (
      "id" uuid DEFAULT gen_random_uuid(),
      "roid" text NULL,
      "status" text NULL,
      "postal_info" text NULL,
      "name" text NULL,
      "org" text NULL,
      "street1" text NULL,
      "street2" text NULL,
      "street3" text NULL,
      "state_province" text NULL,
      "postal_code" text NULL,
      "city" text NULL,
      "country_code" text NULL,
      "voice" text NULL,
      "fax" text NULL,
      "email" text NULL,
      "cl_id" uuid NULL,
      "cr_id" uuid NULL,
      "cr_date" timestamp TIMESTAMP WITH TIME ZONE NULL,
      "up_id" uuid NULL,
      "up_date" timestamp TIMESTAMP WITH TIME ZONE NULL,
      "tr_date" timestamp TIMESTAMP WITH TIME ZONE NULL,
      "auth_info_pw" text NULL,
      "auth_info_ext" text NULL
      "disclose_voice" BOOLEAN NULL,      
      "disclose_email" BOOLEAN NULL
      );