apiVersion: batch/v1
kind: Job
metadata:
  name: contact-flyway-migration
spec:
  template:
    spec:
      containers:
      - name: flyway
        image: flyway/flyway:10
        env:
        - name: FLYWAY_URL
          value: jdbc:postgresql://contact-postgresql:5432/contact
        - name: FLYWAY_USER
          value: contactuser
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  contact-postgresql
              key: password
        - name: FLYWAY_SCHEMAS
          value: contact
        command: ["flyway", "migrate"]
        volumeMounts:
        - mountPath: /flyway/sql
          name: sql
      volumes:
        - name: sql
          configMap:
            name: contact-migration-configmap
      restartPolicy: OnFailure
    