apiVersion: v1
kind: ConfigMap
metadata:
  name: hostquery-config
data:
  application.yml: |
        management:
          endpoints:
            web:
              exposure:
                include: [ "prometheus", "health", "info" ]
          endpoint:
            health:
              show:
                details: always 
