spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/easysix
    driver-class-name: org.postgresql.Driver
    username: easysix
    password: easysix
  jpa:
    hibernate:
      ddl-auto: none  # Disable JPA's automatic schema management, Flyway will handle it
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "health", "info" ]
  endpoint:
    health:
      show:
        details: always