//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.25 at 12:02:43 PM CET 
//


package com.peterpopma.easysix.eppproxy.model.org;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for roleStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="roleStatusType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="ok"/>
 *     &lt;enumeration value="clientLinkProhibited"/>
 *     &lt;enumeration value="linked"/>
 *     &lt;enumeration value="serverLinkProhibited"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "roleStatusType")
@XmlEnum
public enum RoleStatusType {

    @XmlEnumValue("ok")
    OK("ok"),
    @XmlEnumValue("clientLinkProhibited")
    CLIENT_LINK_PROHIBITED("clientLinkProhibited"),
    @XmlEnumValue("linked")
    LINKED("linked"),
    @XmlEnumValue("serverLinkProhibited")
    SERVER_LINK_PROHIBITED("serverLinkProhibited");
    private final String value;

    RoleStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RoleStatusType fromValue(String v) {
        for (RoleStatusType c: RoleStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
