//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.25 at 12:02:43 PM CET 
//


package com.peterpopma.easysix.eppproxy.model.org;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for statusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="statusType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="ok"/>
 *     &lt;enumeration value="hold"/>
 *     &lt;enumeration value="terminated"/>
 *     &lt;enumeration value="clientDeleteProhibited"/>
 *     &lt;enumeration value="clientUpdateProhibited"/>
 *     &lt;enumeration value="clientLinkProhibited"/>
 *     &lt;enumeration value="linked"/>
 *     &lt;enumeration value="pendingCreate"/>
 *     &lt;enumeration value="pendingUpdate"/>
 *     &lt;enumeration value="pendingDelete"/>
 *     &lt;enumeration value="serverDeleteProhibited"/>
 *     &lt;enumeration value="serverUpdateProhibited"/>
 *     &lt;enumeration value="serverLinkProhibited"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "statusType")
@XmlEnum
public enum StatusType {

    @XmlEnumValue("ok")
    OK("ok"),
    @XmlEnumValue("hold")
    HOLD("hold"),
    @XmlEnumValue("terminated")
    TERMINATED("terminated"),
    @XmlEnumValue("clientDeleteProhibited")
    CLIENT_DELETE_PROHIBITED("clientDeleteProhibited"),
    @XmlEnumValue("clientUpdateProhibited")
    CLIENT_UPDATE_PROHIBITED("clientUpdateProhibited"),
    @XmlEnumValue("clientLinkProhibited")
    CLIENT_LINK_PROHIBITED("clientLinkProhibited"),
    @XmlEnumValue("linked")
    LINKED("linked"),
    @XmlEnumValue("pendingCreate")
    PENDING_CREATE("pendingCreate"),
    @XmlEnumValue("pendingUpdate")
    PENDING_UPDATE("pendingUpdate"),
    @XmlEnumValue("pendingDelete")
    PENDING_DELETE("pendingDelete"),
    @XmlEnumValue("serverDeleteProhibited")
    SERVER_DELETE_PROHIBITED("serverDeleteProhibited"),
    @XmlEnumValue("serverUpdateProhibited")
    SERVER_UPDATE_PROHIBITED("serverUpdateProhibited"),
    @XmlEnumValue("serverLinkProhibited")
    SERVER_LINK_PROHIBITED("serverLinkProhibited");
    private final String value;

    StatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StatusType fromValue(String v) {
        for (StatusType c: StatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
