apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  application.yml: |
    server:
      max-http-header-size: 32KB
    spring:
      application:
        name: api-gateway
      cloud:
        gateway:
      # routes are configured as java code       
          httpclient:
            wiretap: true
          httpserver:
            wiretap: true
    logging:
      level:
        root: DEBUG
        reactor:
          netty: INFO
        org:
          springframework:
            cloud:
              gateway: TRACE
    management:
      endpoints:
        web:
          exposure:
            include: [ "prometheus", "health", "info", "gateway" ]