apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.service.targetPort }}
