apiVersion: apps/v1
kind: Deployment
metadata:
  name: contactcreate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contactcreate
  template:
    metadata:
      labels:
        app: contactcreate
    spec:
      containers:
      - name: contactcreate
        image: contactcreate:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: contactcreate-config
        ports:
        - containerPort: 3030
