apiVersion: apps/v1
kind: Deployment
metadata:
  name: contactupdate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contactupdate
  template:
    metadata:
      labels:
        app: contactupdate
    spec:
      containers:
      - name: contactupdate
        image: contactupdate:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: contactupdate-config
        ports:
        - containerPort: 3030
