apiVersion: apps/v1
kind: Deployment
metadata:
  name: contactinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contactinfo
  template:
    metadata:
      labels:
        app: contactinfo
    spec:
      containers:
      - name: contactinfo
        image: contactinfo:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: contactinfo-config
        ports:
        - containerPort: 3030
