apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-postgresql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi