apiVersion: batch/v1
kind: Job
metadata:
  name: host-host-migration
spec:
  template:
    spec:
      containers:
      - name: host
        image: host/host:10
        env:
        - name: FLYWAY_URL
          value: jdbc:postgresql://domain-postgresql:5432/domain
        - name: FLYWAY_USER
          value: domainuser
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  domain-postgresql
              key: password
        - name: FLYWAY_SCHEMAS
          value: domain
        command: ["host", "migrate"]
        volumeMounts:
        - mountPath: /host/sql
          name: sql
      volumes:
        - name: sql
          configMap:
            name: migration-configmap
      restartPolicy: OnFailure
    