apiVersion: v1
kind: ConfigMap
metadata:
  name: contactdelete-config
data:
  application.yml: |
        service:
          simulated-workload: 1000000
        management:
          endpoints:
            web:
              exposure:
                include: [ "prometheus", "health", "info" ]
          endpoint:
            health:
              show:
                details: always 
