apiVersion: apps/v1
kind: Deployment
metadata:
  name: organizationquery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organizationquery
  template:
    metadata:
      labels:
        app: organizationquery
    spec:
      containers:
      - name: organizationquery
        image: organizationquery:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: organizationquery-config
        ports:
        - containerPort: 8080
