server:
  port: 8091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/easysix
    driver-class-name: org.postgresql.Driver
    username: easysix
    password: easysix
  jpa:
    hibernate:
      ddl-auto: none  # Disable JPA's automatic schema management, Flyway will handle it
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        orm:
          jdbc:
            bind: TRACE